// @ts-check

// 隐藏文档专区的侧边栏配置

/**
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // 隐藏文档专区侧边栏 - 自动从 book 目录生成
  bookSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;