// @ts-check

// 小说专区的侧边栏配置

/**
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // 文学专区侧边栏 - 自动从 literature 目录生成
  literatureSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
