// @ts-check

// 小说专区的侧边栏配置

/**
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // 小说专区侧边栏 - 自动从 novel 目录生成
  novelSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;